### ISSUE TITLE
How to serve swagger over https? What are the correct settings?

### ISSUE THREAD

**Issue by siulkilulki** [noirbizarre/flask-restplus#227]
I have working swagger when accessing it over HTTP, but when I try to access it over HTTPS I get following error:
`swagger-ui.min.js:10 Mixed Content: The page at 'https://www.little-hero.tk/api/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.little-hero.tk/api/swagger.json'. This request has been blocked; the content must be served over HTTPS.`

Full printscreen: http://i.imgur.com/jms8bdh.png

What should I do? There is no information in docs. I'm using cloudflare to get https if it helps.

**Comment by ziirish** [comment]
Your issue looks similar to #132
Maybe you can have a look at this issue and try out the proposed fix.

**Comment by cwalkatron** [comment]
Looks like this is a [swagger-js thing](https://github.com/swagger-api/swagger-js/issues/931) that might be fixed in swagger-js 2.1.31 (not sure where this is in swagger-ui). Any chance we can update flask-restplus with the latest swagger?

**Comment by heaje** [comment]
@cwalkatron: I just added the way I fixed this same issue to #132

**Comment by jnguyenx** [comment]
@cwalkatron can you please show more code how you fixed it? I tried to use the ProxyFix without any success.

```
...
from werkzeug.contrib.fixers import ProxyFix

app = Flask(__name__)
app.wsgi_app = ProxyFix(app.wsgi_app)
...
```

Even with that I still get the cross-origin issue.

**Comment by jnguyenx** [comment]
I was missing one line in my nginx.conf `proxy_set_header   X-Forwarded-Proto $scheme;`. Otherwise I used this [nginx config](http://flask.pocoo.org/docs/0.10/deploying/wsgi-standalone/#proxy-setups), but didn't include the ProxyFix.

**Comment by lybroman** [comment]
With the update of werkzeug to 0.15
Now it would work with:
`
app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_proto=1, x_host=1, x_port=1, x_prefix=1)
`

**Comment by davidism** [comment]
Absolutely do not make a broad recommendation to set every value to 1. Each value should be set based on the specific hosting setup for each application. This is relevant to security, and is described in the documentation for `ProxyFix`.

**Comment by ziirish** [comment]
Hi,

The discussions will take place in #223 since your issue is quite similar.

**Comment by ziirish** [comment]
I'm now closing this issue.
Please follow discussions in #223

**Comment by c24b** [comment]
Related to https://github.com/noirbizarre/flask-restplus/issues/132 where I found the correct Fix for Flask-Restplus with Nginx and gunicorn
